# version: "3.8"

services:

  naomi-yolo-client:
    image: naomano/naomi-yolo-client:v1.0.0
    build: ./client
    container_name: naomi-yolo-client
    stdin_open: true
    tty: true
    restart: always
    networks:
      - app-network
    ports:
      - "3000:3000"

  naomi-yolo-backend:
    image: naomano/naomi-yolo-backend:v1.0.0
    build: ./backend
    container_name: naomi-yolo-backend
    stdin_open: true
    tty: true
    restart: always
    networks:
      - app-network
      - db-network
    ports:
      - "8000:8000"
  
  naomi-yolo-mongodb:
    image: mongo:6.0.5
    container_name: naomi-yolo-mongodb
    restart: always
    environment:
      MONGO_SERNAME: root
      MONGO_PASSWORD: example
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - db-network


networks:   
  app-network:
    driver: bridge
  db-network:
    driver: bridge

volumes:
  mongo-data:
    driver: local