# version: "3.8"

services:

  naomi-yolo-client:
    image: namanoo/naomi-yolo-client:v1.0.0
    build: ./client
    container_name: naomi-yolo-client
    stdin_open: true
    tty: true
    restart: always
    networks:
      - app-network
    ports:
      - "3000:80"

  naomi-yolo-backend:
    image: namanoo/naomi-yolo-backend:v1.0.0
    build: ./backend
    container_name: naomi-yolo-backend
    stdin_open: true
    tty: true
    restart: always
    depends_on:
      - naomi-yolo-mongodb
    
    env_file:
      - .env
    networks:
      - app-network
      - db-network
    ports:
      - "500:500"
    
  
  naomi-yolo-mongodb:
    image: mongo:3.0
    container_name: naomi-yolo-mongodb
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE}
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

    env_file:
      - .env
    networks:
      - db-network
    
    



networks:   
  app-network:
    driver: bridge
  db-network:
    driver: bridge

volumes:
  mongo-data:
    driver: local